
server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:25432/demo"
    username: postgres
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    properties:
        hibernate:
          format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

keyservice:
  password: "6416a9ca-4e94-4157-a016-1add5cfdca5c"
  salt: "5c0744940b5c369b"

